"""Aggregates + consistency tooling for the sharded test-plan.

Design: docs/superpowers/specs/2026-07-07-test-plan-scalability-restructure-design.md

Subcommands (all take --plan-dir / --tests-dir, defaulting to the repo paths):
  build     regenerate progress/dashboard.md from clusters/*/allocation.yaml
  check     exit 1 if progress/dashboard.md differs from a fresh build
  validate  allocation state vs the test tree (letters, scenario IDs, dir claims)

`allocation.yaml` is the ONLY input to the dashboard — never parse prose.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

DEFAULT_PLAN_DIR = Path("lex/test_project/test-plan")
DEFAULT_TESTS_DIR = Path("lex/test_project/tests")

# Test folders that deliberately have no owning cluster.
#
# ``design_system`` belongs here rather than under a cluster: its tests assert the
# shape of ``lex/lex_app/design_system/lex_tokens.py``, which is generated verbatim
# by ``@excellencecloudgmbh/lex-tokens``, and they carry no scenario IDs at all —
# so there is nothing for a cluster's allocation to own or number.
EXEMPT_TEST_DIRS = {
    "fixtures",
    "journeys",
    "gate_selftest",
    "others",
    "design_system",
    "__pycache__",
}

VALID_STATUSES = {"planned", "in-flight", "complete", "blocked", "rolled-back"}

GENERATED_BANNER = (
    "<!-- ⚙ GENERATED by .github/scripts/test_plan_aggregates.py build — "
    "DO NOT HAND-EDIT. Edit clusters/*/allocation.yaml and rebuild. -->"
)

LETTER_FILE_RE = re.compile(r"^test_(?P<num>\d+)(?P<letter>[a-z])_[A-Za-z0-9_]+\.py$")
SCENARIO_RE = re.compile(r"Scenario (?P<num>\d+)\.(?P<sid>\d+[a-z]?)\b")
CLUSTER_DIR_RE = re.compile(r"^(?P<num>\d{2})-(?P<slug>[a-z0-9_]+)$")


class AllocationError(Exception):
    """Schema or consistency violation in allocation state."""


@dataclass
class Letter:
    letter: str
    title: str
    scenarios: str
    status: str
    tests: dict
    note: str


@dataclass
class Cluster:
    number: int
    slug: str
    title: str
    max_scenario: int
    test_dirs: list[str]
    letters: list[Letter]
    path: Path  # the clusters/NN-<slug>/ directory


def _require(cond: bool, msg: str) -> None:
    if not cond:
        raise AllocationError(msg)


def load_clusters(plan_dir: Path) -> list[Cluster]:
    """Load and schema-check every clusters/*/allocation.yaml."""
    clusters_dir = plan_dir / "clusters"
    _require(clusters_dir.is_dir(), f"missing {clusters_dir}")
    out: list[Cluster] = []
    for d in sorted(p for p in clusters_dir.iterdir() if p.is_dir()):
        m = CLUSTER_DIR_RE.match(d.name)
        _require(m is not None, f"cluster dir {d.name!r} must match NN-<slug>")
        yml = d / "allocation.yaml"
        _require(yml.is_file(), f"missing {yml}")
        data = yaml.safe_load(yml.read_text())
        for key in ("cluster", "slug", "title", "max_scenario", "letters"):
            _require(key in data, f"{yml}: missing key {key!r}")
        _require(
            int(data["cluster"]) == int(m.group("num"))
            and data["slug"] == m.group("slug"),
            f"{d.name}: dir name disagrees with YAML "
            f"(cluster={data['cluster']}, slug={data['slug']})",
        )
        letters = []
        for letter, spec in (data["letters"] or {}).items():
            _require(
                # Two-letter ids (aa, ab, ...) continue past z. Cluster 1
                # exhausted a-z, and refusing to allocate past that would push
                # batches into clusters they do not belong to.
                re.fullmatch(r"[a-z]{1,2}", str(letter)) is not None,
                f"{yml}: letter {letter!r} must be one or two lowercase letters",
            )
            _require(
                spec.get("status") in VALID_STATUSES,
                f"{yml}: letter {letter!r} has invalid status "
                f"{spec.get('status')!r} (valid: {sorted(VALID_STATUSES)})",
            )
            letters.append(
                Letter(
                    letter=str(letter),
                    title=str(spec.get("title", "")),
                    scenarios=str(spec.get("scenarios", "")),
                    status=spec["status"],
                    tests=spec.get("tests") or {"pass": 0, "skip": 0, "xfail": 0},
                    note=str(spec.get("note", "") or ""),
                )
            )
        letters.sort(key=lambda l: l.letter)
        out.append(
            Cluster(
                number=int(data["cluster"]),
                slug=data["slug"],
                title=str(data["title"]),
                max_scenario=int(data["max_scenario"]),
                test_dirs=list(data.get("test_dirs") or [data["slug"]]),
                letters=letters,
                path=d,
            )
        )
    nums = [c.number for c in out]
    _require(len(nums) == len(set(nums)), f"duplicate cluster numbers: {nums}")
    out.sort(key=lambda c: c.number)
    return out


def render_dashboard(clusters: list[Cluster]) -> str:
    lines = [
        "# Test-Suite Dashboard",
        "",
        GENERATED_BANNER,
        "",
        "> Built from `clusters/*/allocation.yaml`. Per-batch narrative lives in each",
        "> cluster's `batches.md`; scenario intent in `cluster.md`; session narrative",
        "> in `progress/sessions/`.",
        "",
        "## At a glance",
        "",
        "| Cluster | Batches | Max scenario | Pass | Skip | Xfail |",
        "|---|---|---|---|---|---|",
    ]
    for c in clusters:
        t = {"pass": 0, "skip": 0, "xfail": 0}
        for l in c.letters:
            for k in t:
                t[k] += int(l.tests.get(k, 0))
        lines.append(
            f"| {c.number}. {c.title} | {len(c.letters)} | "
            f"{c.max_scenario} | {t['pass']} | {t['skip']} | {t['xfail']} |"
        )
    for c in clusters:
        lines += [
            "",
            f"## {c.number}. {c.title} (`{c.slug}`)",
            "",
            "| Batch | Title | Scenarios | Status | Pass | Skip | Xfail | Note |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for l in c.letters:
            lines.append(
                f"| {c.number}{l.letter} | {l.title} | {l.scenarios} | {l.status} | "
                f"{l.tests.get('pass', 0)} | {l.tests.get('skip', 0)} | "
                f"{l.tests.get('xfail', 0)} | {l.note} |"
            )
    return "\n".join(lines) + "\n"


def build_dashboard(plan_dir: Path) -> None:
    text = render_dashboard(load_clusters(plan_dir))
    (plan_dir / "progress" / "dashboard.md").write_text(text)


def check_dashboard(plan_dir: Path) -> list[str]:
    """Return a list of problems (empty = fresh)."""
    expected = render_dashboard(load_clusters(plan_dir))
    dash = plan_dir / "progress" / "dashboard.md"
    if not dash.is_file():
        return [f"{dash} is missing — run `test_plan_aggregates.py build`"]
    if dash.read_text() != expected:
        return [
            f"{dash} is stale — run `python .github/scripts/test_plan_aggregates.py build` "
            "and commit the result"
        ]
    return []


def validate_allocations(plan_dir: Path, tests_dir: Path) -> list[str]:
    """Cross-check allocation.yaml claims against the test tree.

    Rules (spec §4/§5): every non-exempt test folder is claimed by exactly one
    cluster's test_dirs; every test_<N><letter>_*.py carries the owning cluster's
    number and a letter present in YAML; every `Scenario N.M` docstring ID for the
    owning cluster is <= max_scenario and unique across the cluster's files.
    """
    errors: list[str] = []
    clusters = load_clusters(plan_dir)

    owner_by_dir: dict[str, Cluster] = {}
    for c in clusters:
        for d in c.test_dirs:
            if d in owner_by_dir:
                errors.append(
                    f"test dir {d!r} claimed by clusters "
                    f"{owner_by_dir[d].number} and {c.number}"
                )
            owner_by_dir[d] = c

    on_disk = {
        p.name for p in tests_dir.iterdir()
        if p.is_dir() and p.name not in EXEMPT_TEST_DIRS
        and not p.name.startswith(("_", "."))
    }
    for name in sorted(on_disk - set(owner_by_dir)):
        errors.append(
            f"test dir {name!r} has no owning cluster — add it to a cluster's "
            "test_dirs in allocation.yaml (or to EXEMPT_TEST_DIRS if deliberate)"
        )

    for c in clusters:
        seen: dict[str, Path] = {}  # scenario id -> first file
        yaml_letters = {l.letter for l in c.letters}
        for d in c.test_dirs:
            folder = tests_dir / d
            if not folder.is_dir():
                errors.append(f"cluster {c.number}: test dir {d!r} does not exist")
                continue
            for f in sorted(folder.glob("test_*.py")):
                m = LETTER_FILE_RE.match(f.name)
                if m:
                    if int(m.group("num")) != c.number:
                        errors.append(
                            f"{f}: filename cluster {m.group('num')} but folder "
                            f"{d!r} belongs to cluster {c.number}"
                        )
                    elif m.group("letter") not in yaml_letters:
                        errors.append(
                            f"{f}: letter {m.group('num')}{m.group('letter')} not "
                            f"declared in {c.path / 'allocation.yaml'}"
                        )
                text = f.read_text(errors="replace")
                for sm in SCENARIO_RE.finditer(text):
                    if int(sm.group("num")) != c.number:
                        continue  # cross-references to other clusters are prose
                    sid = f"{sm.group('num')}.{sm.group('sid')}"
                    base = int(re.match(r"\d+", sm.group("sid")).group())
                    if base > c.max_scenario:
                        errors.append(
                            f"{f}: scenario {sid} exceeds max_scenario="
                            f"{c.max_scenario} in {c.path / 'allocation.yaml'}"
                        )
                    prev = seen.get(sid)
                    if prev is not None and prev != f:
                        errors.append(
                            f"duplicate scenario {sid}: {prev} and {f}"
                        )
                    seen.setdefault(sid, f)
    return errors


def _cli() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("build", "check", "validate"))
    parser.add_argument("--plan-dir", type=Path, default=DEFAULT_PLAN_DIR)
    parser.add_argument("--tests-dir", type=Path, default=DEFAULT_TESTS_DIR)
    args = parser.parse_args()
    if args.command == "build":
        build_dashboard(args.plan_dir)
        print(f"wrote {args.plan_dir / 'progress' / 'dashboard.md'}")
        return 0
    problems = (
        check_dashboard(args.plan_dir)
        if args.command == "check"
        else validate_allocations(args.plan_dir, args.tests_dir)
    )
    for p in problems:
        print(f"- {p}")
    print("OK" if not problems else f"{len(problems)} problem(s)")
    return 0 if not problems else 1


if __name__ == "__main__":
    sys.exit(_cli())
