from __future__ import absolute_import

import logging
import re
import sys
import warnings
from pathlib import Path

import urllib3

from django.core.cache import CacheKeyWarning
from google.oauth2 import service_account

"""
Django settings for lex_app project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

from lex.runtime_config import (
    derive_repo_name,
    resolve_local_sqlite_path,
    resolve_project_root,
)


def traces_sampler(sampling_context):
    if sampling_context == "/health":
        # Drop this transaction, by setting its sample rate to 0%
        return 0
    else:
        # Default sample rate for all others (replaces traces_sample_rate)
        return 0.1


if (
    os.getenv("DEPLOYMENT_ENVIRONMENT") != "DEV"
    and os.getenv("DEPLOYMENT_ENVIRONMENT") is not None
):
    sentry_sdk.init(
        dsn="https://a3aa24a7fccd42dbbb7457e6402b5443@o1318244.ingest.sentry.io/6573603",
        integrations=[
            DjangoIntegration(),
        ],
        environment=os.getenv("DEPLOYMENT_ENVIRONMENT"),
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production.
        traces_sampler=traces_sampler,
        # If you wish to associate users to errors (assuming you are using
        # django.contrib.auth) you may enable sending PII data.
        send_default_pii=True,
    )


warnings.simplefilter("ignore", CacheKeyWarning)

# Suppress urllib3's InsecureRequestWarning. The Keycloak admin client may run
# with TLS verification disabled (KEYCLOAK_VERIFY_SSL), which otherwise floods
# local logs with one InsecureRequestWarning per request. Set
# LEX_SUPPRESS_INSECURE_WARNING=False to restore the warning while debugging TLS.
if os.getenv("LEX_SUPPRESS_INSECURE_WARNING", "True").lower() == "true":
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Quiet Python's warning system so local startup logs stay clean — e.g. Django's
# "Accessing the database during app initialization is discouraged" RuntimeWarning
# and any other library warnings raised through the `warnings` module. Settings is
# imported before app initialisation, so the filter is installed in time to catch
# warnings raised from AppConfig.ready(). Set LEX_SUPPRESS_WARNINGS=False to restore
# Python's default warning behaviour while debugging.
if os.getenv("LEX_SUPPRESS_WARNINGS", "True").lower() == "true":
    warnings.filterwarnings("ignore")

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = resolve_project_root(os.getenv("PROJECT_ROOT"), os.getcwd()).as_posix()
os.environ.setdefault("PROJECT_ROOT", PROJECT_ROOT)
NEW_BASE_DIR = Path(PROJECT_ROOT).parent.as_posix()
sys.path.append(NEW_BASE_DIR)

ASGI_APPLICATION = "lex_app.asgi.application"

# Use Redis channel layer when deployed OR when Celery is active.
# InMemoryChannelLayer is per-process, so Celery workers (separate processes)
# cannot send WebSocket messages to the ASGI server's consumers.
# Since Celery already requires Redis as its broker, we reuse it here.
_use_redis_channel_layer = (
    os.getenv("DEPLOYMENT_ENVIRONMENT") is not None
    or os.getenv("CELERY_ACTIVE", "False").lower() == "true"
    or os.getenv("C_FORCE_ROOT") == "True"
)

if _use_redis_channel_layer:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
            "CONFIG": {
                "hosts": [
                    (
                        f"redis://{os.getenv('REDIS_USERNAME')}:{os.getenv('REDIS_PASSWORD')}@{os.getenv('REDIS_HOST')}/2"
                        if os.getenv("DEPLOYMENT_ENVIRONMENT") is not None
                        else "redis://127.0.0.1:6379/2"
                    )
                ],
                "capacity": 100000,
                "expiry": 10,
                "prefix": f"{os.getenv('INSTANCE_RESOURCE_IDENTIFIER', 'local')}:",
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

STORAGES = {
    "default": {
        "BACKEND": "lex.utilities.storage.custom_storage.CustomDefaultStorage",
    },
    "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},


}

SHAREPOINT_APP_CLIENT_ID = os.getenv("SHAREPOINT_APP_CLIENT_ID")
SHAREPOINT_API_CERTIFICATE_PATH = os.getenv("SHAREPOINT_API_CERTIFICATE_PATH")
SHAREPOINT_API_CERTIFICATE_THUMBPRINT = os.getenv(
    "SHAREPOINT_API_CERTIFICATE_THUMBPRINT"
)
SHAREPOINT_API_TENANT_NAME = os.getenv("SHAREPOINT_API_TENANT_NAME")
SHAREPOINT_URL = os.getenv("SHAREPOINT_URL", "local")
SHAREPOINT_STATIC_DIR = "static"
SHAREPOINT_MEDIA_DIR = "uploads"

if os.getenv("STORAGE_TYPE") == "SHAREPOINT":
    STORAGES = {
        "default": {
            "BACKEND": "django_sharepoint_storage.SharePointCloudStorageUtils.Media",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        },
    }
    MEDIA_ROOT = "uploads/"

if os.getenv("STORAGE_TYPE") == "GCS":
    STORAGES = {
        "default": {
            "BACKEND": "lex.utilities.utils.gcs_utils.Media",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        },
    }
    GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME")
    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
        os.path.join(NEW_BASE_DIR, "django-storages", "gcpCredentials.json"),
    )
    MEDIA_ROOT = "uploads/"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY", default="pjlulvaa77lteno-_y6!oxb%63xqiaw4%n%1or&77a!x9@nkd+"
)
QUACKBACK_WIDGET_SECRET = os.getenv("QUACKBACK_WIDGET_SECRET", "")

# SECURITY WARNING: don't run with debug turned on in production!
if os.getenv("LEX_ENVIRONMENT_TAG", "envvar_not_existing") == "dev":
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = [
    os.getenv("DOMAIN_HOSTED", "localhost"),
    "127.0.0.1",
    "localhost",
    os.environ.get("POD_IP", default="envvar_not_existing"),
]

LOGIN_REDIRECT_URL = "/process_admin/all"

CSRF_TRUSTED_ORIGINS = [
    "https://*." + os.getenv("DOMAIN_HOSTED", "localhost"),
    "http://localhost:3000",
]

# Fail fast on missing critical configuration when deployed, instead of silently
# falling back to "localhost". A missing DOMAIN_HOSTED makes ALLOWED_HOSTS only
# match localhost, so every WebSocket/CSRF check rejects the real instance
# hostname -> the frontend continuously redirects to /server-not-ready. A
# crash-looping pod surfaces the misconfiguration immediately; a silently broken
# one does not. Only enforced in deployed pods (DEPLOYMENT_ENVIRONMENT set), so
# local development and tests are unaffected.
if os.getenv("DEPLOYMENT_ENVIRONMENT") is not None:
    from django.core.exceptions import ImproperlyConfigured

    if not os.getenv("DOMAIN_HOSTED"):
        raise ImproperlyConfigured(
            "DOMAIN_HOSTED must be set when DEPLOYMENT_ENVIRONMENT is set; without "
            "it ALLOWED_HOSTS only matches 'localhost' and all WebSocket/CSRF "
            "checks reject the real instance hostname."
        )

    if _use_redis_channel_layer:
        _missing_redis = [
            name
            for name in ("REDIS_HOST", "REDIS_USERNAME", "REDIS_PASSWORD")
            if not os.getenv(name)
        ]
        if _missing_redis:
            raise ImproperlyConfigured(
                "Redis channel layer is active but required env vars are missing: "
                + ", ".join(_missing_redis)
            )

REACT_APP_BUILD_PATH = (
    Path(__file__).resolve().parent.parent / Path("react/build")
).as_posix()
repo_name = derive_repo_name(PROJECT_ROOT, os.getcwd())
LEGACY_MEDIA_ROOT = os.path.join(NEW_BASE_DIR, f"{repo_name}/")
LOG_FILE_PATH = os.path.join(NEW_BASE_DIR, f"{repo_name}/{repo_name}.log")


# Note: LOGGING is configured at the bottom of this file, after all env-dependent
# variables (IS_DEPLOYED, CONSOLE_LEVEL, ROOT_LEVEL) have been resolved.


# Application definition

INSTALLED_APPS = [
    "channels",
    "lex.utilities.apps.UtilitiesConfig",
    "lex.core.apps.CoreConfig",
    "lex.authentication.apps.AuthenticationConfig",
    "lex.audit_logging.apps.LoggingConfig",
    "lex.api.apps.ApiConfig",
    "lex.process_admin.apps.ProcessAdminConfig",
    "lex.lex_app.apps.LexAppConfig",
    "simple_history",
    "celery",
    "django_celery_beat",
    "lex.react.apps.ReactConfig",
    "markdown",
    "lex.lex_app.apps.CustomAdminConfig",  # Custom admin config to prevent auth admin conflicts
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_api_key",
    "django.contrib.postgres",
    "django_db_views",
    "oauth2_authcodeflow",
    "lex.legacy_data.apps.LegacyDataConfig",
]

if not repo_name.startswith("lex"):
    INSTALLED_APPS.append(repo_name)


CRISPY_FAIL_SILENTLY = not DEBUG

OIDC_ENABLED = all(
    os.getenv(key)
    for key in (
        "KEYCLOAK_URL",
        "KEYCLOAK_REALM",
        "OIDC_RP_CLIENT_ID",
        "OIDC_RP_CLIENT_SECRET",
    )
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Compress text responses, above all the SPA bundle: it is a single ~6 MB
    # chunk that gzips to ~1.9 MB, so this is a 3.3x cut on every first load and
    # on any asset the browser has not cached yet. Placed high so it wraps the
    # response on the way out, which is what GZipMiddleware requires.
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "oauth2_authcodeflow.middleware.BearerAuthMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "lex.authentication.middleware.ApiKeyAwareLoginRequiredMiddleware",
    "oauth2_authcodeflow.middleware.RefreshSessionMiddleware",
    "oauth2_authcodeflow.middleware.RefreshAccessTokenMiddleware",
    "lex.api.middleware.keycloak_permissions.KeycloakPermissionsMiddleware",
]

ROOT_URLCONF = "lex_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates"), "generic_app/submodels/"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lex_app.wsgi.application"

DISABLE_SERVER_SIDE_CURSORS = True

db_username = os.getenv("POSTGRES_USERNAME", "django")
kubernetes = not os.getenv("KUBERNETES_ENGINE", "NONE") == "NONE"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "default_cache",
        "TIMEOUT": None,
    },
    "oidc": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "oidc_cache",
    },
    "redis": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": (
            f"redis://{os.getenv('REDIS_USERNAME')}:{os.getenv('REDIS_PASSWORD')}@{os.getenv('REDIS_HOST')}/2"
            if os.getenv("DEPLOYMENT_ENVIRONMENT") is not None
            else "redis://127.0.0.1:6379/2"
        ),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Optional: silently ignore redis down-time
            "IGNORE_EXCEPTIONS": True,
        },
    },
    "local": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }

}


DATABASES = {
    "local": {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': resolve_local_sqlite_path(PROJECT_ROOT, repo_name).as_posix(),
    },
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": f"db_{repo_name.lower()}",
        "USER": "django",
        "PASSWORD": "lundadminlocal",
        "HOST": "localhost",
        "PORT": "5432",
    },
    "GCP": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.getenv("DATABASE_NAME", "envvar_not_existing"),
        "USER": db_username,
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "envvar_not_existing"),
        "HOST": os.getenv("DATABASE_DOMAIN", "envvar_not_existing"),
        "PORT": "5432",
        "TEST": {
            "NAME": os.getenv("DATABASE_NAME", "envvar_not_existing"),
        },
    },
    "DOCKER-COMPOSE": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.getenv("DATABASE_NAME", "envvar_not_existing"),
        "USER": db_username,
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "envvar_not_existing"),
        "HOST": os.getenv("DATABASE_DOMAIN", "envvar_not_existing"),
        "PORT": "5432",
        "TEST": {
            "NAME": os.getenv("DATABASE_NAME", "envvar_not_existing"),
        },
    },
    "K8S": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.getenv("DATABASE_NAME", "envvar_not_existing"),
        "USER": db_username,
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "envvar_not_existing"),
        "HOST": os.getenv("DATABASE_DOMAIN", "envvar_not_existing"),
        "PORT": "5432",
        "OPTIONS": {"sslmode": "disable"},
        "TEST": {
            "NAME": os.getenv("DATABASE_NAME", "envvar_not_existing"),
        },
    },
}
DATABASE_DEPLOYMENT_TARGET = os.getenv("DATABASE_DEPLOYMENT_TARGET", "default")
if DATABASE_DEPLOYMENT_TARGET != "local":
    DATABASES["default"] = DATABASES[DATABASE_DEPLOYMENT_TARGET]
else:
    DATABASES["default"] = DATABASES["local"]

# Django only honors DISABLE_SERVER_SIDE_CURSORS when it is set *inside* the
# per-database config dict (it is read from connection.settings_dict), not as a
# module-level setting. Server-side (named) cursors break behind a
# transaction-pooling proxy (cloud-sql-proxy / pgbouncer): the DECLARE and a
# later FETCH can land on different backend connections, raising
# "cursor _django_curs_... does not exist". Disable them on every PostgreSQL
# alias so .iterator() falls back to client-side reads.
for _db_config in DATABASES.values():
    if "postgresql" in _db_config.get("ENGINE", ""):
        _db_config["DISABLE_SERVER_SIDE_CURSORS"] = True

MIGRATION_MODULES = {}


# CELERY STUFF
# Celery Broker Configuration - Redis
CELERY_BROKER_URL = (
    f"redis://{os.getenv('REDIS_USERNAME')}:{os.getenv('REDIS_PASSWORD')}@{os.getenv('REDIS_HOST')}/1"
    if os.getenv("DEPLOYMENT_ENVIRONMENT") is not None
    else "redis://127.0.0.1:6379/1"
)

# Celery Result Backend Configuration - Redis (changed from PostgreSQL)
CELERY_RESULT_BACKEND = (
    f"db+postgresql://{db_username}:{os.getenv('POSTGRES_PASSWORD', 'envvar_not_existing')}@{os.getenv('DATABASE_DOMAIN', 'envvar_not_existing')}/{os.getenv('DATABASE_NAME', 'envvar_not_existing')}"
    if os.getenv("DEPLOYMENT_ENVIRONMENT") is not None
    else f"db+postgresql://django:lundadminlocal@localhost/db_{repo_name.lower()}"
)

# Celery Configuration
CELERY_CACHE_BACKEND = "default"
CELERY_ACCEPT_CONTENT = ["application/json", "pickle"]
CELERY_TASK_SERIALIZER = "pickle"
CELERY_RESULT_SERIALIZER = "pickle"
CELERY_CREATE_MISSING_QUEUES = True
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_PERSISTENT = True
CELERY_TASK_DEFAULT_QUEUE = os.getenv("INSTANCE_RESOURCE_IDENTIFIER", "celery")

# Redis-specific Celery configuration
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "global_keyprefix": f"{os.getenv('INSTANCE_RESOURCE_IDENTIFIER', 'celery')}:",
    "visibility_timeout": float("inf"),
}
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    "global_keyprefix": f"{os.getenv('INSTANCE_RESOURCE_IDENTIFIER', 'celery')}:",
    "visibility_timeout": float("inf"),
}

# Task execution configuration
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True

# Result expiration (Redis cleanup)
CELERY_RESULT_EXPIRES = 3600  # 1 hour

# Use django-celery-beat's DatabaseScheduler so `celery beat` reads
# PeriodicTask / ClockedSchedule rows from the DB by default. Overridable
# via the ``CELERY_BEAT_SCHEDULER`` env var — useful for local chaos
# testing where the default ``celery.beat:PersistentScheduler`` (a small
# on-disk file) is more reliable than DatabaseScheduler on misconfigured
# Postgres timezones or stalled-sync edge cases.
CELERY_BEAT_SCHEDULER = os.getenv(
    "CELERY_BEAT_SCHEDULER",
    "django_celery_beat.schedulers:DatabaseScheduler",
)

# Flower monitoring configuration
FLOWER_ADDRESS = os.getenv("FLOWER_ADDRESS", "127.0.0.1")
FLOWER_PORT = int(os.getenv("FLOWER_PORT", "5555"))
FLOWER_URL_PREFIX = os.getenv("FLOWER_URL_PREFIX", "")

# Enhanced Celery Active Configuration
# Support both CELERY_ACTIVE and legacy C_FORCE_ROOT for backward compatibility
CELERY_ACTIVE = os.getenv("CELERY_ACTIVE", "False").lower() == "true"
CELERY_TASK_TIMEOUT = int(os.getenv("CELERY_TASK_TIMEOUT", "3600"))  # 1 hour
CELERY_MAX_RETRIES = int(os.getenv("CELERY_MAX_RETRIES", "3"))
CELERY_RETRY_DELAY = int(os.getenv("CELERY_RETRY_DELAY", "60"))  # seconds

# Cluster-wide cascade cancellation (Redis cancel index).
# When enabled, CalculationModel.cancel discovers child task_ids that
# other worker pods registered (via the Redis tree index) and revokes
# them too. Inert whenever CELERY_ACTIVE is off or no Redis is reachable.
LEX_CLUSTER_CANCEL_ENABLED = (
    os.getenv("LEX_CLUSTER_CANCEL_ENABLED", "true").lower() == "true"
)
LEX_CLUSTER_CANCEL_TREE_TTL_SECONDS = int(
    os.getenv("LEX_CLUSTER_CANCEL_TREE_TTL_SECONDS", "14400")  # 4 hours
)
LEX_CLUSTER_CANCEL_MARKER_TTL_SECONDS = int(
    os.getenv("LEX_CLUSTER_CANCEL_MARKER_TTL_SECONDS", "3600")  # 1 hour
)

# Legacy support for C_FORCE_ROOT (backward compatibility)
try:
    c_force_root = os.getenv("C_FORCE_ROOT")
    if c_force_root == "True":
        CELERY_ACTIVE = True
    # If CELERY_ACTIVE is already True from environment, keep it True
    # Only set to False if both C_FORCE_ROOT and CELERY_ACTIVE are not set to True
    elif not CELERY_ACTIVE:
        CELERY_ACTIVE = False
except Exception as e:
    # If there's any error, fall back to the CELERY_ACTIVE environment variable value
    pass

# Make celery_active available as a module-level variable for backward compatibility
celery_active = CELERY_ACTIVE

# ---------------------------------------------------------------------------
# Celery worker-recovery knobs (see docs/celery-worker-recovery/plan.md)
#
# These drive the heartbeat + supervisor system that detects dead workers and
# requeues their in-flight task back to the broker, bounded by a max-retries
# budget. When the budget is exceeded the supervisor writes a FAILURE to the
# result backend so the parent's AsyncResult.get() raises.
#
# Master switch: LEX_TASK_RECOVERY_ENABLED disables every signal handler, the
# heartbeat thread, and the beat-driven supervisor sweep when off.
#
# Default is OFF. Recovery leaves a stuck IN_PROGRESS row untouched at startup
# (the liveness-aware sweep skips rows a tracked recovery task owns), on the
# assumption that a recovery-supervisor pod is running to requeue/resume them.
# When that pod is not running (local dev, CI, and any deployment that has not
# provisioned it) the row is orphaned IN_PROGRESS forever. Defaulting OFF keeps
# the startup sweep in its blind-abort mode so a stuck row is reset on restart.
# Deployments that DO run the supervisor pod opt in with
# LEX_TASK_RECOVERY_ENABLED=true (the recovery-supervisor manifest already sets
# it explicitly). An explicit env var overrides in either direction.
# ---------------------------------------------------------------------------
LEX_TASK_RECOVERY_ENABLED = (
    os.getenv("LEX_TASK_RECOVERY_ENABLED", "false").lower() == "true"
)
LEX_TASK_HEARTBEAT_INTERVAL = int(os.getenv("LEX_TASK_HEARTBEAT_INTERVAL", "5"))
LEX_TASK_HB_TTL_MULTIPLIER = int(os.getenv("LEX_TASK_HB_TTL_MULTIPLIER", "3"))
LEX_TASK_SUPERVISOR_SCAN_INTERVAL = int(
    os.getenv("LEX_TASK_SUPERVISOR_SCAN_INTERVAL", "10")
)
LEX_TASK_MAX_RETRIES = int(os.getenv("LEX_TASK_MAX_RETRIES", "4"))

# ---------------------------------------------------------------------------
# Worker self-termination knobs
# (see docs/superpowers/specs/2026-06-05-worker-self-termination-design.md)
#
# Drive the two in-framework triggers that make an idle worker exit so its
# KEDA ScaledJob pod terminates: a task_revoked cancel fast-path and an idle
# watchdog. Both are additionally gated behind a non-local DEPLOYMENT_TARGET,
# so local dev and CI are unaffected regardless of these values.
# Surfaced here for operator discoverability; lex/lex_app/celery.py reads the
# same env vars directly.
# ---------------------------------------------------------------------------
LEX_WORKER_IDLE_SHUTDOWN_ENABLED = (
    os.getenv("LEX_WORKER_IDLE_SHUTDOWN_ENABLED", "true").strip().lower() == "true"
)
LEX_WORKER_IDLE_SHUTDOWN_SECONDS = float(
    os.getenv("LEX_WORKER_IDLE_SHUTDOWN_SECONDS", "30")
)

if LEX_TASK_RECOVERY_ENABLED:
    # django-celery-beat's DatabaseScheduler ingests CELERY_BEAT_SCHEDULE at
    # startup via update_from_dict, so this entry lands as a PeriodicTask row
    # without manual provisioning.
    #
    # ``expires`` is critical: beat keeps enqueuing this sweep regardless of
    # whether a worker is consuming. Without an expiry, a few minutes of worker
    # downtime piles up hundreds of identical sweep messages in the broker
    # queue, and when the worker returns it chews through the whole backlog
    # even though each older sweep is logically obsoleted by the next one.
    # We expire each message after one full interval so the queue depth for
    # this task can never exceed ~1 message at a time.
    CELERY_BEAT_SCHEDULE = {
        **(globals().get("CELERY_BEAT_SCHEDULE") or {}),
        "lex-celery-recovery-sweep": {
            "task": "lex.lex_app.celery_recovery.supervisor.sweep_dead_workers",
            "schedule": float(LEX_TASK_SUPERVISOR_SCAN_INTERVAL),
            # Route to a dedicated queue consumed ONLY by the recovery pod
            # (celery worker -B -Q recovery). Keeps the sweep off the main
            # KEDA-watched queue so it never inflates the worker scaling signal
            # nor gets eaten by a scaled-up real worker. expires bounds backlog.
            "options": {
                "queue": "recovery",
                "expires": float(LEX_TASK_SUPERVISOR_SCAN_INTERVAL),
            },
        },
    }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CORS_ORIGIN_ALLOW_ALL = True

DATA_UPLOAD_MAX_NUMBER_FIELDS = None
KEYCLOAK_URL = os.getenv("KEYCLOAK_URL")
KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM")
OIDC_RP_CLIENT_ID = os.getenv("OIDC_RP_CLIENT_ID")
OIDC_RP_CLIENT_SECRET = os.getenv("OIDC_RP_CLIENT_SECRET")
OIDC_RP_CLIENT_UUID = os.getenv("OIDC_RP_CLIENT_UUID")
if OIDC_ENABLED:
    OIDC_OP_USER_ENDPOINT = (
        f"{KEYCLOAK_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/userinfo"
    )
    OIDC_OP_DISCOVERY_DOCUMENT_URL = (
        f"{KEYCLOAK_URL}/realms/{KEYCLOAK_REALM}/.well-known/openid-configuration"
    )
    AUTHENTICATION_BACKENDS = (
        "oauth2_authcodeflow.auth.AuthenticationBackend",
        "django.contrib.auth.backends.ModelBackend",
    )
else:
    OIDC_OP_USER_ENDPOINT = ""
    OIDC_OP_DISCOVERY_DOCUMENT_URL = ""
    AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

OIDC_RP_SCOPES = ["openid", "email", "profile"]
_django_base_path = os.getenv("DJANGO_BASE_PATH", "").strip().strip("/")
_admin_exempt_patterns = [
    r"^/admin(?:/|$)",
    r"^/static-django/admin(?:/|$)",
]
if _django_base_path:
    _escaped_base_path = re.escape(_django_base_path)
    _admin_exempt_patterns.extend(
        [
            rf"^/{_escaped_base_path}/admin(?:/|$)",
            rf"^/{_escaped_base_path}/static-django/admin(?:/|$)",
        ]
    )

OIDC_MIDDLEWARE_NO_AUTH_URL_PATTERNS = [
    "/manifest.json",
    "manifest.json",
    "/health",
    "/favicon.ico",
    "api/user/",
    "/api/user",
    "api/health",
    "api/active-calculations",
    "/api/active-calculations",
    "api/favicon.ico",
    "api/api/user/",
    "api/api/user",
    "api/api/active-calculations",
    "/api/api/active-calculations",
] + _admin_exempt_patterns

OIDC_MIDDLEWARE_NO_REFRESH_URL_PATTERNS = [
    r"^/health$",
    r"^/favicon\.ico$",
] + _admin_exempt_patterns
OIDC_RP_USE_PKCE = False
SESSION_COOKIE_SECURE = os.getenv("DEPLOYMENT_ENVIRONMENT") is not None
CSRF_COOKIE_SECURE = os.getenv("DEPLOYMENT_ENVIRONMENT") is not None
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
OIDC_UNUSABLE_PASSWORD = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "*"
    # add any other hosts your front-end uses
]


# JWT_SECRET_KEY = SECRET_KEY
# JWT_ALGORITHM = 'HS256'
# JWT_ACCESS_TOKEN_LIFETIME = timedelta(minutes=5)  # Short-lived
# JWT_REFRESH_GRACE_PERIOD = timedelta(minutes=10)  # Grace period for refresh
# JWT_EXPIRATION_HOURS = 2


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "lex.authentication.authentication_backends.BearerMiddlewareAuthentication.BearerMiddlewareAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        # other authentication classes, if needed
    ],
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    # FIXME: maybe use this at some point (for giving individual access rights):
    # "DEFAULT_PERMISSION_CLASSES": ['rest_framework_api_key.permissions.HasAPIKey' | 'rest_framework.permissions.IsAuthenticated']
}
API_KEY_CUSTOM_HEADER = "HTTP_API_KEY"

if os.getenv("SENDGRID_API_KEY", "envvar_not_existing") != "envvar_not_existing":
    SENDGRID_API_KEY = os.environ["SENDGRID_API_KEY"]
else:
    SENDGRID_API_KEY = "improperlyConfigured"

EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
SENDGRID_ECHO_TO_STDOUT = True

# ##################################################
# ################## END AUTH ######################
# ##################################################

CORS_ORIGIN_WHITELIST = [
    "https://" + os.getenv("DOMAIN_HOSTED", "localhost:3000"),
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "*",
]

LANGUAGE_CODE = "en-us"

# TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

# Timezone-aware UTC is the framework datetime convention (ADR:
# docs/releases/tz-decision-usetz-true.md). Every datetime is stored as a true
# UTC instant and each client renders it in the viewer's own zone. Columns are
# already `timestamptz` (Django's PostgreSQL backend uses `timestamp with time
# zone` regardless of USE_TZ), so this needs no column-type migration; only the
# instant-correcting `rebase_incident_datetimes` management command re-anchors
# the window of user-entered values written while the connection zone was
# mistakenly UTC (see the command's docstring and the ADR).
USE_TZ = True

# Display / naive-input zone. Storage is ALWAYS UTC under USE_TZ=True, so this
# never changes what's stored — it sets (a) how the server renders datetimes
# (admin, PDFs, timezone.localtime, DRF's wire offset) and (b) how a naive input
# with no offset is interpreted. Defaults to Europe/Berlin — the framework's
# historical zone and the majority of deployments — and is overridable per
# instance via LEX_TIME_ZONE. With the Berlin default a Berlin instance is
# correct with the CURRENT frontend (a naive pick is read as Berlin -> the right
# instant); instances elsewhere set LEX_TIME_ZONE and/or ship the frontend
# offset-send so non-Berlin data entry is correct too. (Previously coupled to
# USE_TZ for django_celery_beat, which has since been retired.)
TIME_ZONE = os.getenv("LEX_TIME_ZONE", "Europe/Berlin")

# NOTE: the former BUG-025 workaround (a DATETIME_FORMAT that appended an
# explicit 'Z' to naive-UTC values) is intentionally removed. Under USE_TZ=True
# aware datetimes serialize with a real offset natively, so no override is
# needed.

# Run the PostgreSQL connection session in TIME_ZONE so fetched `timestamptz`
# values come back as aware datetimes in the display zone (Berlin) instead of
# UTC. This makes str()/repr, `.date()`/`.hour`, and model `__str__` render local
# with NO per-field or per-model changes — storage stays UTC and the instant is
# unchanged (23:30Z reads back as 00:30+01:00 == the original instant). Django's
# date/time-part lookups already inject an explicit `AT TIME ZONE`, so they are
# unaffected. Postgres-only: the session zone is what makes psycopg render
# timestamptz locally; SQLite works in UTC under USE_TZ and is left unset.
if "postgresql" in DATABASES["default"].get("ENGINE", ""):
    DATABASES["default"]["TIME_ZONE"] = TIME_ZONE

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static-django/"

STATIC_ROOT = "/static"

if os.getenv("STORAGE_TYPE") == "LEGACY" or not os.getenv("STORAGE_TYPE"):
    if os.getenv("KUBERNETES_ENGINE", "NONE") == "NONE":
        MEDIA_ROOT = os.path.join(NEW_BASE_DIR, f"{repo_name}/")
        MEDIA_URL = os.path.join(NEW_BASE_DIR, f"{repo_name}/")
        USER_REPORT_ROOT = os.path.join(NEW_BASE_DIR, f"{repo_name}/")
    else:
        # this section is not in effect when a cloud storage option is used.
        # Check DjangoProcessAdminGeneric/gcsUtils.py or
        # DjangoProcessAdminGeneric/sharepoint/SharePointCloudStorageUtils.py for replacement.
        MEDIA_ROOT = f"/app/storage/uploads"
        MEDIA_URL = f"/app/storage/uploads"

        USER_REPORT_ROOT = "/app/storage/reports/"

IS_DEPLOYED = os.getenv("DEPLOYMENT_ENVIRONMENT") is not None

# Console handler level: INFO by default everywhere.
# Override locally with LOG_LEVEL=DEBUG if you need third-party debug output.
CONSOLE_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()

# oauth2_authcodeflow: keep quiet unless explicitly requested
OAUTH2_LEVEL = "INFO" if IS_DEPLOYED else os.getenv("LOG_LEVEL", "INFO").upper()

# Root logger level: respect LOG_LEVEL env var, default to INFO.
# This prevents django-lifecycle, OpenTelemetry, OIDC middleware etc.
# from flooding the console with DEBUG messages during local development.
ROOT_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()

# lex framework namespace level: controls debug output for lex.* loggers ONLY.
# Set LEX_LOG_LEVEL=DEBUG to see the framework's logger.debug(...) output without
# the third-party debug noise that LOG_LEVEL=DEBUG would pull in (root stays at
# ROOT_LEVEL, so non-lex DEBUG records are dropped at their logger).
LEX_LOG_LEVEL = os.getenv("LEX_LOG_LEVEL", "INFO").upper()

# The console handler must be at least as verbose as the most verbose logger that
# routes to it, otherwise it would drop lex.* DEBUG records before emitting them.
# Lower numeric level = more verbose (DEBUG=10, INFO=20).
CONSOLE_HANDLER_LEVEL = min(
    logging.getLevelName(CONSOLE_LEVEL),
    logging.getLevelName(LEX_LOG_LEVEL),
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {"format": "{levelname} {asctime} {message}", "style": "{"},
        "ws_md": {"format": "\n{message}", "style": "{"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
            "level": CONSOLE_HANDLER_LEVEL,
        },
        "ws": {
            "()": "lex.audit_logging.handlers.WebSocketHandler.WebSocketHandler",
            "level": "DEBUG",
            "formatter": "ws_md",
        },
    },
    "loggers": {
        # Framework namespace: LEX_LOG_LEVEL=DEBUG surfaces lex.* debug logs only.
        # More specific child loggers (e.g. lex.calclog) keep their own config.
        "lex": {
            "handlers": ["console"],
            "level": LEX_LOG_LEVEL,
            "propagate": False,
        },
        "lex.calclog": {
            "handlers": ["ws", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "oauth2_authcodeflow": {
            "handlers": ["console"],
            "level": OAUTH2_LEVEL,
            "propagate": False,
        },
        # Silence noisy third-party DEBUG output
        "django_lifecycle": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "opentelemetry": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "azure": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": ROOT_LEVEL,
    },
}

INSTANCE_CONTROLLER_BASE_URL = os.getenv(
    "INSTANCE_CONTROLLER_BASE_URL",
    "https://test.excellence-cloud.dev",
)

KEYCLOAK_SETUP_CALLBACK_URL = os.getenv(
    "KEYCLOAK_SETUP_CALLBACK_URL",
    "http://127.0.0.1:8000/api/bootstrap/keycloak/",
)


DATA_UPLOAD_MAX_MEMORY_SIZE = None

# Simple History Configuration
# Set to False to disable automatic exclusion of Django built-in models
SIMPLE_HISTORY_AUTO_EXCLUDE_BUILTIN = True

# Additional models to exclude from history tracking (beyond the built-in exclusions)
# Add model names (lowercase) that you specifically don't want to track
SIMPLE_HISTORY_EXCLUDED_MODELS = [
    # Example: 'temporarydata', 'cachedresult'
]

# Primary Key Configuration
# Default auto-created primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
