"""
Cluster 1m: ``lex`` CLI commands — every ``.run/*.run.xml`` invocation must wire through.

Intent
------

``lex setup`` scaffolds 14 PyCharm run configurations under ``.run/``.
Each one invokes the ``lex`` CLI with a specific subcommand. The
contract this test enforces is the most operator-visible one in the
framework:

    Every ``.run/*.run.xml`` file generated by
    ``generate_pycharm_configs`` must reference a subcommand that
    actually resolves through the ``lex`` CLI — either as an explicit
    ``@lex.command(...)`` Click handler or as a Django management
    command that ``_install_dynamic_commands()`` will register.

Sub-cluster 1a (`test_1a_lex_setup.py`) only checks three of the
fourteen files (Init / Start / Streamlit). The CLI helper-tests in
``lex/tests/unit/cli/test_lex_cli.py`` validate individual builders
(Celery, Flower, MCP) but never assert the cross-file contract that
"every command an operator can click in PyCharm actually works".

This sub-cluster closes that gap. We:

* parse every generated ``.run.xml`` for its ``SCRIPT_NAME`` +
  ``PARAMETERS`` pair,
* take the first token of the parameter string (the subcommand),
* assert the subcommand is reachable via the in-process Click group
  OR is a registered Django management command,
* pin the explicit ``@lex.command`` registry so any rename without a
  matching ``.run.xml`` update fails here, not in the operator's
  PyCharm.

All scenarios are **fast** (no subprocess, no real server). Click's
``CliRunner`` invokes the group in-process; Django bootstrap runs
once per class.

Scenario numbering extends ``docs/test-plan/test-clusters.md`` —
sub-cluster 1m picks up at **1.102**.
"""

from __future__ import annotations

import re
import shlex
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest import TestCase

from click.testing import CliRunner
from generate_pycharm_configs import generate_pycharm_configs
from lex.bin.lex import _SKIP_BOOTSTRAP_COMMANDS, lex

import pytest

pytestmark = pytest.mark.init

# Explicit ``@lex.command(...)`` names the framework depends on. Pinned
# here so a rename that leaves a ``.run.xml`` (or the docs) behind fails
# in CI rather than in the operator's PyCharm.
#
# The ``ai-*`` commands are no longer among them, bar one. Their options ship
# with lex-mcp-local so that adding a command does not need a lex-app release,
# and ``lex`` resolves them against the installed package rather than
# registering them here — see ``_LexGroup`` in ``lex/bin/lex.py``. They are
# covered below, derived from that package rather than pinned here, because a
# roster restated in this file is exactly what the move was getting rid of.
#
# ``ai-update`` stays: it is a bootstrap that must run before lex-mcp-local
# exists, and it is the recovery path when the installed one is too old.
EXPLICIT_COMMANDS = frozenset({
    "celery",
    "celery-workers",
    "flower",
    "streamlit",
    "start",
    "setup",
    "setup-with-ai",
    "ai-update",
})

# Deprecated spellings kept runnable for people following older docs and
# support macros, but kept out of ``lex --help`` so it advertises one spelling
# per command. They used to be a second ``hidden=True`` click command each,
# duplicating the whole option block; the group now normalises the separator,
# so these resolve rather than being registered.
HIDDEN_ALIASES = frozenset({
    "ai_issue_report",
    "ai_verify",
})


def _delegated_commands():
    """The ``ai-*`` names the installed lex-mcp-local provides, or ``None``.

    Derived, never restated. lex-app deliberately does not know this list --
    that is the whole point of delegating -- so the test reads it from the same
    registry the CLI does.
    """
    try:
        from lex_mcp.cli import command_names
    except ImportError:
        return None
    return frozenset(command_names())

# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------
# Regex: extract value="..." for a named option in a .run.xml file.
_OPTION_RE = re.compile(
    r'<option\s+name="(?P<key>SCRIPT_NAME|PARAMETERS)"\s+value="(?P<val>[^"]*)"'
)


def _parse_run_file(path: Path) -> dict:
    """Pull out SCRIPT_NAME + PARAMETERS from a ``.run.xml``."""
    out = {}
    for match in _OPTION_RE.finditer(path.read_text(encoding="utf-8")):
        out[match.group("key")] = match.group("val")
    return out


def _first_token(parameters: str) -> str:
    """First whitespace-delimited token, ignoring any quoted-prompt prefix."""
    if not parameters:
        return ""
    # ``shlex.split`` handles the ``$Prompt:Test label:lex.tests$`` form
    # as a single token starting with ``$``; we only need the first
    # token regardless.
    try:
        tokens = shlex.split(parameters, posix=True)
    except ValueError:
        # Fall back to whitespace split for malformed quote pairs.
        tokens = parameters.split()
    return tokens[0] if tokens else ""


def _scaffold_run_dir(workdir: Path) -> Path:
    """Run ``generate_pycharm_configs`` into ``workdir`` and return ``.run/``."""
    (workdir / "pyproject.toml").write_text(
        "[project]\nname='cli-contract-test'\n",
        encoding="utf-8",
    )
    generate_pycharm_configs(str(workdir))
    return workdir / ".run"


# ---------------------------------------------------------------------
# 1.102 — Generated file set parity
# ---------------------------------------------------------------------
class TestCluster01m_RunFileSetParity(TestCase):
    """Every ``.run/*.run.xml`` declared by ``generate_pycharm_configs``
    is on disk after a fresh scaffold — no orphans, no missing files.

    This is the canary for "I removed Test_Audit from the source dict
    but the constant on disk still has it" drift.
    """

    EXPECTED_FILES = frozenset({
        "Init.run.xml",
        "Setup_With_AI.run.xml",
        "Start.run.xml",
        "Flower.run.xml",
        "Celery_Worker.run.xml",
        "Make_migrations.run.xml",
        "Migrate.run.xml",
        "Streamlit.run.xml",
        "Create_DB.run.xml",
        "Flush_DB.run.xml",
    })

    def test_1_102_scaffold_produces_complete_run_file_set(self):
        """1.102: scaffolding writes every expected ``.run.xml`` and
        nothing extra. Operators see the same PyCharm tray on every
        machine.
        """
        with TemporaryDirectory() as tmp:
            run_dir = _scaffold_run_dir(Path(tmp))
            on_disk = {p.name for p in run_dir.glob("*.run.xml")}

        self.assertEqual(
            on_disk, self.EXPECTED_FILES,
            f"\n  missing: {self.EXPECTED_FILES - on_disk}"
            f"\n  unexpected: {on_disk - self.EXPECTED_FILES}",
        )


# ---------------------------------------------------------------------
# 1.103 — Every .run file invokes the `lex` CLI
# ---------------------------------------------------------------------
class TestCluster01m_RunFileScriptName(TestCase):
    """All ``.run/*.run.xml`` set ``SCRIPT_NAME=lex`` — they invoke
    our CLI, not a stray ``manage.py`` or system Python.
    """

    def test_1_103_every_run_xml_uses_lex_script(self):
        """1.103: ``SCRIPT_NAME`` is ``lex`` for every generated file.

        Regression guard: a copy-paste of a different SCRIPT_NAME
        would silently bypass the CLI's setup logic (env handling,
        Django bootstrap, etc.) and fail in surprising ways.
        """
        with TemporaryDirectory() as tmp:
            run_dir = _scaffold_run_dir(Path(tmp))
            for run_file in sorted(run_dir.glob("*.run.xml")):
                parsed = _parse_run_file(run_file)
                self.assertEqual(
                    parsed.get("SCRIPT_NAME"), "lex",
                    f"{run_file.name}: SCRIPT_NAME must be 'lex'; "
                    f"got {parsed.get('SCRIPT_NAME')!r}.",
                )


# ---------------------------------------------------------------------
# 1.104 — Subcommand resolution
# ---------------------------------------------------------------------
class TestCluster01m_RunFileSubcommandResolution(TestCase):
    """The first token of every ``.run`` file's PARAMETERS must
    resolve to a real subcommand on the ``lex`` Click group, OR to
    a Django management command that the CLI's dynamic-forwarding
    layer will register.
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        # Explicit @lex.command names attached at module import time.
        cls.explicit_commands = set(lex.commands.keys())

        # Django management commands — bootstrap once for the class.
        from lex.bin.lex import _bootstrap_django

        get_commands, _ = _bootstrap_django()
        cls.django_commands = set(get_commands().keys())

    def _assert_subcommand_exists(self, subcommand: str, source: str) -> None:
        if subcommand in self.explicit_commands:
            return
        if subcommand in self.django_commands:
            return
        self.fail(
            f"{source}: subcommand {subcommand!r} is neither an "
            f"explicit `lex` Click command nor a registered Django "
            f"management command. Either add it to lex/bin/lex.py "
            f"as @lex.command(name={subcommand!r}) or remove the "
            f".run.xml entry that references it.\n"
            f"  Known explicit commands: {sorted(self.explicit_commands)}\n"
            f"  (Django command count: {len(self.django_commands)})"
        )

    def test_1_104_every_run_subcommand_resolves(self):
        """1.104: every ``.run.xml`` first-token is a real subcommand.

        This is the cross-file contract that nothing else asserts:
        ``generate_pycharm_configs.py`` (declares the .run files)
        and ``lex/bin/lex.py`` (declares the CLI) must stay in sync.
        """
        with TemporaryDirectory() as tmp:
            run_dir = _scaffold_run_dir(Path(tmp))
            for run_file in sorted(run_dir.glob("*.run.xml")):
                parsed = _parse_run_file(run_file)
                first = _first_token(parsed.get("PARAMETERS", ""))
                self.assertTrue(
                    first,
                    f"{run_file.name}: PARAMETERS is empty "
                    f"({parsed.get('PARAMETERS')!r}) — every .run "
                    "must invoke at least one subcommand.",
                )
                self._assert_subcommand_exists(first, run_file.name)


# ---------------------------------------------------------------------
# 1.105 — Explicit Click registry
# ---------------------------------------------------------------------
class TestCluster01m_ExplicitClickCommands(TestCase):
    """Pin the set of explicit ``@lex.command(...)`` registrations.

    Removing or renaming one of these is what would silently break a
    ``.run.xml``; we want a hard failure here so the maintainer
    sees the breakage at the CLI source-file level.
    """

    EXPECTED_EXPLICIT_COMMANDS = EXPLICIT_COMMANDS

    def test_1_105_explicit_commands_are_all_registered(self):
        """1.105: every explicit Click handler we depend on is on the group."""
        registered = set(lex.commands.keys())
        missing = self.EXPECTED_EXPLICIT_COMMANDS - registered
        self.assertFalse(
            missing,
            f"`lex` Click group is missing explicit commands: {sorted(missing)}\n"
            f"  Registered: {sorted(registered)}",
        )

    def test_1_106_skip_bootstrap_set_matches_explicit_handlers(self):
        """1.106: the ``_SKIP_BOOTSTRAP_COMMANDS`` allow-list is a subset
        of the explicit commands.

        ``main()`` reads this set to decide whether to invoke
        ``django.setup()``. Listing a name here that isn't actually
        a Click handler would silently fall through to the dynamic
        path — same drift class as the .run/lex contract above.
        """
        registered = set(lex.commands.keys())
        leaked = _SKIP_BOOTSTRAP_COMMANDS - registered
        self.assertFalse(
            leaked,
            f"_SKIP_BOOTSTRAP_COMMANDS contains names that aren't "
            f"explicit Click handlers: {sorted(leaked)}",
        )


# ---------------------------------------------------------------------
# 1.107 — `lex --help` invocability
# ---------------------------------------------------------------------
class TestCluster01m_HelpInvocability(TestCase):
    """Every explicit subcommand answers ``--help`` cleanly via the
    in-process Click runner. This is the cheapest possible "the
    command actually exists" assertion.

    We deliberately do NOT exec ``--help`` for dynamic Django
    commands (they would trigger Django setup and be slow); 1.108
    covers that side via ``django.core.management.get_commands``.
    """

    EXPECTED_EXPLICIT_COMMANDS = EXPLICIT_COMMANDS

    def test_1_107_lex_root_help_lists_explicit_commands(self):
        """1.107: ``lex --help`` exits 0 and names every explicit command
        an operator is meant to type.

        Deprecated spellings (``HIDDEN_ALIASES``) are excluded: they stay
        runnable — 1.108 proves that — but ``hidden=True`` keeps them out
        of the listing so the help advertises one spelling per command.
        """
        runner = CliRunner()
        result = runner.invoke(lex, ["--help"])
        self.assertEqual(
            result.exit_code, 0,
            f"`lex --help` failed: exit={result.exit_code}\n"
            f"output: {result.output}",
        )
        for name in self.EXPECTED_EXPLICIT_COMMANDS - HIDDEN_ALIASES:
            self.assertIn(
                name, result.output,
                f"`lex --help` does not mention {name!r}.",
            )

    def test_1_107b_deprecated_aliases_stay_out_of_root_help(self):
        """1.107b: hidden aliases still run but are not advertised.

        Listing the same command twice under two spellings is exactly the
        ambiguity the canonical hyphenated names exist to remove. Resolution,
        not registration: the group normalises the separator now, where each
        alias used to be a second ``hidden=True`` command duplicating the whole
        option block.
        """
        import click

        runner = CliRunner()
        result = runner.invoke(lex, ["--help"])
        ctx = click.Context(lex)
        for name in HIDDEN_ALIASES:
            with self.subTest(command=name):
                self.assertIsNotNone(
                    lex.get_command(ctx, name),
                    f"deprecated alias {name!r} no longer resolves — "
                    f"drop it from HIDDEN_ALIASES if the spelling was retired "
                    f"on purpose.",
                )
                self.assertNotIn(
                    name, result.output,
                    f"`lex --help` lists the deprecated spelling {name!r}.",
                )

    def test_1_107c_delegated_commands_are_listed_and_runnable(self):
        """1.107c: what lex-mcp-local provides shows up in `lex --help`.

        The other half of the delegation. lex-app registers none of these, so
        nothing in its own source would fail if the group stopped resolving
        them -- `lex ai-verify` would simply become "No such command" at a
        customer, with `lex --help` quietly one section shorter.
        """
        import click

        delegated = _delegated_commands()
        if delegated is None:
            self.skipTest("needs lex-mcp-local installed or on the path")

        self.assertTrue(delegated, "lex-mcp-local registered no commands")
        runner = CliRunner()
        result = runner.invoke(lex, ["--help"])
        ctx = click.Context(lex)
        for name in delegated:
            with self.subTest(command=name):
                self.assertNotIn(
                    name, lex.commands,
                    f"{name!r} is registered in lex-app after all; it is "
                    f"supposed to come from lex-mcp-local.",
                )
                self.assertIsNotNone(lex.get_command(ctx, name))
                self.assertIn(name, result.output)
                self.assertEqual(
                    runner.invoke(lex, [name, "--help"]).exit_code, 0,
                    f"`lex {name} --help` did not exit 0.",
                )

    def test_1_108_each_explicit_subcommand_help_exits_zero(self):
        """1.108: ``lex <cmd> --help`` exits 0 for every explicit handler.

        Catches Click decorator typos / signature regressions that
        ``--help`` surfaces but a "real" run wouldn't because the
        handler bails earlier.
        """
        runner = CliRunner()
        for name in self.EXPECTED_EXPLICIT_COMMANDS:
            with self.subTest(command=name):
                result = runner.invoke(lex, [name, "--help"])
                self.assertEqual(
                    result.exit_code, 0,
                    f"`lex {name} --help` failed: exit={result.exit_code}\n"
                    f"output: {result.output}\n"
                    f"exception: {result.exception!r}",
                )


# ---------------------------------------------------------------------
# 1.109 — Django commands referenced by .run files
# ---------------------------------------------------------------------
class TestCluster01m_DjangoSideContract(TestCase):
    """Every ``.run`` file that delegates to a Django management
    command (``init``, ``migrate``, ``makemigrations``, ``flush``,
    ``test``, ``create_db``) must point at a name Django actually
    knows about — otherwise the CLI's dynamic forwarding falls
    through to ``execute_from_command_line`` which fails with a
    less-helpful error.
    """

    DJANGO_DELEGATED_COMMANDS = frozenset({
        "init",          # Init.run.xml
        "migrate",       # Migrate.run.xml
        "makemigrations",  # Make_migrations.run.xml
        "flush",         # Flush_DB.run.xml
        "test",          # Test_*.run.xml
        "create_db",     # Create_DB.run.xml
    })

    def test_1_109_every_delegated_command_is_a_real_django_command(self):
        """1.109: every Django-side subcommand a ``.run.xml`` references
        is registered with Django's command loader."""
        from lex.bin.lex import _bootstrap_django

        get_commands, _ = _bootstrap_django()
        registered = set(get_commands().keys())
        missing = self.DJANGO_DELEGATED_COMMANDS - registered
        self.assertFalse(
            missing,
            f"PyCharm .run files reference Django commands that are "
            f"not registered: {sorted(missing)}.\n"
            f"  Either add them under "
            f"`lex/lex_app/management/commands/` or update "
            f"`generate_pycharm_configs.py` to stop referencing them.",
        )


if __name__ == "__main__":  # pragma: no cover
    unittest.main()

