# Generated by Django 5.1.2 on 2024-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInputFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='input_files/')),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOutputFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='output_files/')),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overview', models.TextField(blank=True, null=True)),
                ('files_with_analysis', models.TextField(blank=True, null=True)),
                ('structure', models.JSONField(blank=True, null=True)),
                ('detailed_structure', models.JSONField(blank=True, null=True)),
                ('functionalities', models.TextField(blank=True, null=True)),
                ('models_fields', models.JSONField(blank=True, null=True)),
                ('classes_and_their_paths', models.JSONField(blank=True, null=True)),
                ('business_logic_calcs', models.TextField(blank=True, null=True)),
                ('specification_doc', models.TextField(blank=True, null=True)),
                ('generated_code', models.TextField(blank=True, null=True)),
                ('input_files', models.ManyToManyField(to='lex_ai.projectinputfiles')),
                ('output_files', models.ManyToManyField(to='lex_ai.projectoutputfiles')),
            ],
        ),
    ]
