"""Render the LEX Streamlit theme as config: TOML text, a file, or CLI flags.

Two delivery paths, one source:

* **CLI flags** (primary) — `lex streamlit` appends `--theme.<path>=<value>`.
  Location-independent, so a dashboard launched from any working directory is
  themed identically.
* **TOML file** (fallback) — a generated `.streamlit/config.toml`, which
  Streamlit resolves relative to the *current working directory*. That is
  exactly why flags are primary.

Both are rendered from one `build_full_config()` call, so they cannot disagree.

Streamlit rejects unrecognised config options, so key placement is not
cosmetic: `GLOBAL_ONLY_KEYS` must stay out of the per-mode blocks, and dotted
keys must become nested tables rather than literal `"a.b"` keys.
"""
from __future__ import annotations

import json
from pathlib import Path

from .mapping import _MODES, GLOBAL_ONLY_KEYS, build_streamlit_theme


def _nest(flat: dict) -> dict:
    """Expand dotted keys into nested sub-tables.

    ``{"sidebar.backgroundColor": "#283C50"}`` ->
    ``{"sidebar": {"backgroundColor": "#283C50"}}``

    Single level only: ``"a.b.c"`` becomes ``{"a": {"b.c": ...}}``, not a
    two-deep tree. Every key we emit today is at most one dot deep
    (``sidebar.*``); revisit this if that changes.
    """
    nested: dict = {}
    for key, value in flat.items():
        if "." in key:
            table, leaf = key.split(".", 1)
            nested.setdefault(table, {})[leaf] = value
        else:
            nested[key] = value
    return nested


def build_full_config(tokens: dict) -> dict:
    """Return the whole `[theme]` config tree, ready to render.

    ``[theme]`` carries the global-only keys plus the light values as the base;
    ``[theme.light]`` / ``[theme.dark]`` carry the per-mode keys.

    The returned tree ALIASES shared state: list values (the chart palettes)
    are the same objects held by the ``TOKENS`` constant, not copies. Render
    it, don't mutate it — mutating a nested list would corrupt the process-wide
    source of truth.
    """
    base = build_streamlit_theme(tokens, "light")

    theme: dict = _nest({k: v for k, v in base.items() if k not in GLOBAL_ONLY_KEYS})
    theme.update({k: v for k, v in base.items() if k in GLOBAL_ONLY_KEYS})

    for mode in _MODES:
        per_mode = base if mode == "light" else build_streamlit_theme(tokens, mode)
        theme[mode] = _nest(
            {k: v for k, v in per_mode.items() if k not in GLOBAL_ONLY_KEYS}
        )

    return {"theme": theme}


def _toml_value(value: object) -> str:
    """Render a Python value as TOML. JSON is a valid subset for these types."""
    if isinstance(value, bool):
        # Explicit for intent: TOML requires lowercase `true`/`false`. json.dumps
        # happens to agree today; this branch keeps that a guarantee, not a
        # coincidence we inherited.
        return "true" if value else "false"
    return json.dumps(value)


def _cli_value(value: object) -> str:
    """Render a value for a ``--theme.<key>=VALUE`` flag.

    Deliberately NOT ``_toml_value``. Streamlit takes a flag value verbatim, so a
    JSON-quoted string arrives with its quotes still attached
    (``"#14b4b4"`` rather than ``#14b4b4``) and is then rejected as an invalid
    colour. Streamlit *silently skips* invalid colours instead of erroring, so
    reusing the TOML encoder here produced a launch that started perfectly and
    applied no theme at all — invisible to every check except looking at a page.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple)):
        # List options ARE expressible on the CLI: Streamlit json.loads the
        # value (see app_session._parse_and_populate_chart_colors), so these
        # must stay JSON — unlike plain strings, which must be bare.
        return json.dumps(list(value))
    return str(value)


def _render_table(name: str, table: dict) -> list[str]:
    """Render one TOML table, recursing into sub-tables after its scalars."""
    lines = [f"[{name}]"]
    sub_tables = {}
    for key, value in table.items():
        if isinstance(value, dict):
            sub_tables[key] = value
        else:
            lines.append(f"{key} = {_toml_value(value)}")
    lines.append("")
    for sub_name, sub_table in sub_tables.items():
        lines.extend(_render_table(f"{name}.{sub_name}", sub_table))
    return lines


def render_config_toml(config: dict) -> str:
    """Render the config tree as TOML text."""
    lines = [
        "# GENERATED by lex.lex_app.streamlit.theme — DO NOT EDIT BY HAND.",
        "# Source of truth: lex/lex_app/streamlit/theme/tokens.py",
        "# Regenerate via the lex Streamlit theme writer (see that package).",
        "",
    ]
    for name, table in config.items():
        lines.extend(_render_table(name, table))
    return "\n".join(lines).rstrip() + "\n"


def write_config(path: str | Path, tokens: dict) -> Path:
    """Write the generated theme config to ``path``. Returns the path."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_config_toml(build_full_config(tokens)), encoding="utf-8")
    return target


def theme_cli_flags(tokens: dict) -> list[str]:
    """Return `--theme.<path>=<value>` flags for `streamlit run`.

    Emits every key for the base and both mode blocks, so the flags alone theme a
    dashboard regardless of the working directory. Value encoding differs from
    TOML: plain strings go bare (a quoted colour is discarded as invalid) while
    lists stay JSON, because Streamlit ``json.loads`` those.
    """
    flags: list[str] = []

    def emit(prefix: str, table: dict) -> None:
        for key, value in table.items():
            if isinstance(value, dict):
                emit(f"{prefix}.{key}", value)
            else:
                flags.append(f"--{prefix}.{key}={_cli_value(value)}")

    emit("theme", build_full_config(tokens)["theme"])
    return flags


def compose_launch_flags(user_args: list[str], tokens: dict) -> list[str]:
    """Return the theme flags to append to a `streamlit run` invocation.

    Any `--theme.*` option the caller already specified is OMITTED, so an
    explicit customer flag always wins. We suppress rather than reorder because
    Streamlit's flag-precedence behaviour is not something we should depend on.

    Recognises both `--opt=value` and `--opt value` forms.
    """
    user_options = set()
    for arg in user_args:
        if not arg.startswith("--"):
            continue
        user_options.add(arg[2:].split("=", 1)[0])

    return [
        flag
        for flag in theme_cli_flags(tokens)
        if flag[2:].split("=", 1)[0] not in user_options
    ]
